In [ ]:
homepath="../../Untitled Folder/"
companypath="../materials/"
path=companypath

# 기본

In [ ]:
import os
import pandas as pd
import numpy as np

# 전처리

In [ ]:
# normalization
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# inverse_transform()

In [ ]:
df=pd.read_csv(path+"iris.csv")
df_1=df.head()
df_1

In [ ]:
nor_minmax=MinMaxScaler().fit(df_1.iloc[:,:-1]) # 규칙을 만듦

In [ ]:
arr_nor=nor_minmax.transform(df_1.iloc[:,:-1]) #데이터를 넣음
df_minmax=pd.DataFrame(arr_nor,columns=df_1.columns[:4])
df_minmax

In [ ]:
pd.DataFrame(nor_minmax.inverse_transform(arr_nor),columns=df_1.columns[:4])
# 역변환

# 통계
https://datadoctorblog.com/2020/09/16/Py-prepare-skill-test-03-stat/

In [ ]:
# correlation
from scipy.stats import pearsonr # pearson
from scipy.stats import spearmanr # spearman
from scipy.stats import kendalltau # kendall

# pandas에 제공되는 .corr()
df=pd.read_csv(path+"bike.csv")
df[["season","holiday"]].corr() #method인자에 pearson, kendall, spearman 입력가능

# SciPy
#pearsonr(ser1,ser2)
## (0.8257047804016666, 0.04292079349918977) # 검정통계량, p-value

In [ ]:
# independent test
from scipy.stats import chi2_contingency

# t-test
from scipy.stats import ttest_1samp
from scipy.stats import ttest_rel
from scipy.stats import ttest_ind

# variance
from scipy.stats import bartlett
from scipy.stats import levene
#from scipy.stats import f.cdf # F-test(cumulative distrubution function of F distribution)

# ANOVA
from scipy.stats import f_oneway
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from statsmodels.stats.multicomp import pairwise_tukeyhsd # post-process of ANOVA

In [ ]:
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

ser_1 = pd.Series([2, 5, 3, 4, 6, 2, 3])
ser_2 = pd.Series([7, 3, 6, 5, 2, 6, 7])
ser_3 = pd.Series([9, 11, 4, 8, 2, 15, 3])

df_aov = pd.DataFrame([ser_1, ser_2, ser_3]).transpose().melt()

formula = "value ~ C(variable)" # C() 범주형 변수임을 명시
lm = ols(formula, df_aov).fit()
anova_lm(lm)
#.resid : 잔차추출
#.params : 모델 객체에서 회귀 계수 및 절편 추출

# 머신러닝

## 데이터 분할

In [ ]:
from sklearn.model_selection import train_test_split
df.sample(n=2, random_state=123).shape

## 모델링
https://datadoctorblog.com/2020/09/16/Py-prepare-skill-test-04-ML/

In [ ]:
from sklearn.neighbors import KNeighborsClassifier # k-NN
from sklearn.neighbors import KNeighborsRegressor # k-NN
from sklearn.cluster import AgglomerativeClustering # 계층적 준집 분석
from sklearn.cluster import KMeans # K-means
from statsmodels.formula.api import ols # 선형회귀
from sklearn.linear_model import LinearRegression  # 선형회귀
from statsmodels.api import Logit # 로지스틱 회귀
from sklearn.linear_model import LogisticRegression # 로지스틱 회귀
from sklearn.tree import DecisionTreeClassifier # Decision Tree
from sklearn.tree import DecisionTreeRegressor # Decision Tree
from sklearn.naive_bayes import GaussianNB # Naive Bayes

# classification tree : 이진분류시, Gini index 기반의 CART 사용
# regrassion tree : 노드 분류할때 평균&표준편차 사용함.

In [ ]:
from statsmodels.formula.api import ols
model_1 = ols("SepalLength ~ SepalWidth + PetalLength", data = df).fit()
model_1.summary()
#.resid : 잔차추출
#.params : 모델 객체에서 회귀 계수 및 절편 추출
df["pred"]=model_1.predict(df)
df.head(3)

#R-squared가 높음 (설명력, 결정계수)
# intercept : 절편
# 검정통계량 t
# 검정통계량의 절대값보다 큰 t가 나올 확률 P가 0이나 다름없다.
# => 귀무가설을 기각하고 대립가설을 채택해서 2.2299라는 것이 통계적으로 의미가 있고
# 독립변수 PW에 대한 계수가 0이 아니라 계산된 특정값을 가진다.
# 그래서 y = 2.2299 x + 1.0836 이런 수식이 나오게 된다.

In [ ]:
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression(fit_intercept = True, normalize = True)
model_1.fit(X = df[["SepalWidth", "PetalLength"]], y = df["SepalLength"])
model_1.coef_ #회귀 계수
## array([0.59552475, 0.47192004])

model_1.intercept_ #절편
## 2.249140160383228

In [ ]:
from statsmodels.api import Logit
model_2 = Logit(endog = df["is_setosa"], exog = df.iloc[:, :2]).fit()
model_2.summary()
model_2.params # coefficient
## SepalLength    -7.529945
## SepalWidth     13.130734
## dtype: float64

model.pvalues
model.tvalues

np.exp(model_2.params) # OR, Odds Ratio
## SepalLength         0.000537
## SepalWidth     504202.644901
## dtype: float64

pred=model.predict(df)
(pred>0.5)+0

In [ ]:
from sklearn.linear_model import LogisticRegression
model_2 = LogisticRegression(solver = "newton-cg").fit(X = df.iloc[:, :2], y = df["is_setosa"])

model_2.coef_
## array([[-3.38829663,  3.16451973]])

np.exp(model_2.coef_) # OR, Odds Ratio
## array([[ 0.03376614, 23.67736985]])

In [ ]:
from sklearn.cluster import KMeans
model_3 = KMeans(n_clusters = 3, random_state = 123).fit(X = df.iloc[:, :4])

model_3.cluster_centers_ #각 군집의 중심점 출력
## array([[5.006     , 3.428     , 1.462     , 0.246     ],
##        [6.85      , 3.07368421, 5.74210526, 2.07105263],
##        [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

model_3.labels_ #각 데이터가 속하는 군집의 번호
## array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
##        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
##        0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
##        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
##        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
##        1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
##        1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2])

from sklearn.metrics import silhouette_score
silhouette_score(X = df_x, labels = model_3.labels_)
## 0.5528190123564102

In [ ]:
from sklearn.cluster import AgglomerativeClustering
model_4 = AgglomerativeClustering(n_clusters = 3).fit(X = df.iloc[:, :4])

model_4.labels_
## array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
##        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
##        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
##        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
##        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
##        2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
##        2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int64)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_5 = KNeighborsClassifier(n_neighbors = 5).fit(X = df.iloc[:, :4], y = df["Species"])
model_5.predict(df.iloc[:, :4])[:20]
## array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa'], dtype=object)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model_6 = DecisionTreeClassifier().fit(X = df.iloc[:, :4], y = df["Species"])

model_6.feature_importances_
## array([0.        , 0.01333333, 0.56405596, 0.42261071])

model_6.predict(X = df.iloc[:, :4])[:20]
## array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
##        'setosa', 'setosa'], dtype=object)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_7 = GaussianNB().fit(X = df.iloc[:, :4], y = df["Species"])

model_7.class_prior_ #종속변수 사전확률

model_7.theta_ #계수같은 느낌?

model_7.classes_
## array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

model_7.predict_proba(df.iloc[:, :4])[:4, ] # 'setosa', 'versicolor', 'virginica'
## array([[1.00000000e+00, 1.35784265e-18, 7.11283512e-26],
##        [1.00000000e+00, 1.51480769e-17, 2.34820051e-25],
##        [1.00000000e+00, 1.07304179e-18, 2.34026774e-26],
##        [1.00000000e+00, 1.46619543e-17, 2.95492722e-25]])

# 거리?

In [ ]:
scipy spatial distance
euclidean() #유클리드 거리
cityblock() #맨하탄
cosine() #코사인 유사도
jaccard() #자카드 유사도

## 평가 - 회귀

In [ ]:
from sklearn.metrics import mean_absolute_error # MAE
from sklearn.metrics import mean_absolute_percentage_error # MAPE
#print(abs((ser_true_value - ser_pred_value) / ser_true_value).sum() * 100) # MAPE

from sklearn.metrics import mean_squared_error # MSE
#mean_squared_error() ** 0.5 ## RMSE

## 평가 - 분류

In [ ]:
from sklearn.metrics import roc_auc_score # AUC

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

# 다중 공선성
- 회귀 모델의 독립변수간 강한 상관관계가 나타나는것

#### patsy
- dmatrices
    - 수식을 기반으로 데이터 행렬을 생성
    - 분산 팽창 계수 확인을 위해 입력데이터를 전처리 할때 필요
    - return_type인자에 "dataframe"으로 설정 시 후처리 용이

#### statsmodels
- variance_inflation_factor
    - 분산 팽창 계수 연산
    - 연산을 위해 반복문 또는 list comprehension사용

In [ ]:
patsy - dmatrices()
statsmodels - variance_inflation_factor()

In [ ]:
import pandas as pd
from patsy import dmatrices
from statsmodels.formula.api import ols
from statsmodels.stats.outliers_influence import variance_inflation_factor

df=pd.read_csv(path+"bike.csv")

df_model=df.loc[:,"temp":"casual"]
#formula="casual ~ " +" + ".join(df_sub.columns[:-1])
y,X=dmatrices("casual ~ temp + atemp + humidity + windspeed",
             df_model, return_type="dataframe")

vif=pd.DataFrame()
vif["VIF Factor"]=[variance_inflation_factor(X.values,i) for i in range(X.shape[1])]
vif["features"]=X.columns
vif

# temp, atemp, intercept의 다중공선성이 높게 나옴. 이들중에 한개는 빼줘야함

# ----------------------------------------

# 데이터구조

In [ ]:
# 기본
{"A": [1, 2, 3], "B": ["a", "b"]}
# numpy
np.array([[1, 2], [3, 4]])
np.arange(5, 10, 2) # 수열
np.r_[1, 2, 5:9] # 이산, 연속 수열 생성가능
# pandas
pd.Series([1, 2, 3])
pd.DataFrame({"A": [1, 2], "B": ["a", "b"]})
pd.DataFrame(data = [[1, 2], [3, 4]], columns = ["a", "b"])

# 데이터 읽기

In [ ]:
df = pd.read_csv(path+"bike.csv")
#df = pd.read_csv(path+"bike.csv", sep="\t")

# 객체 알아보기

In [ ]:
set([1, 1, 2, 3, 3])
len([3, 5, 7, 8])
type([1, 2, 3])

# numpy
arr = np.array([[1, 2, 3], [10, 9, 8]])
arr.min() ## 1
arr.max() ## 10
arr.mean() ## 5.5
arr.argmax() ## 3
arr.argmin() ## 0
arr.ndim ## 2, 차원
arr.shape ## (2, 3), 각 차원의 길이
arr.dtype ## dtype('int32'), 데이터 타입

# pandas : Series
ser = pd.Series([1, 3, 5, 8, 4])
ser.min() ## 1
ser.max() ## 8
ser.mean() ## 4.2
ser.var() ## 6.700000000000001
ser.std() ## 2.5884358211089573
ser.skew() ## 0.5016571985664492 #왜도
ser.kurt() ## 0.7952773446201817 #첨도
ser.idxmin() ## 0
ser.idxmax() ## 3
ser.ndim ## 1
ser.shape # (5,)
ser.dtype # dtype('int64')

df["Sepal_Length"].quantile(q=0.25) # 사분위수
df=df.rename(columns={"Sepal.Length":"SL"}) # 컬럼명 변경

# 연산
- **: 지수 연산. 지수에 0.5을 입력할 경우 제곱근(root)으로 연산되어 np.sqrt() 대체 가능
- //: 나눗셈의 몫. 연령대 같은 경우 다섯살, 열살 단위로 나눌 때 유용하게 사용할 수 있다.
- %: 나눗셈의 나머지. 홀수와 짝수를 판별할 때 유용하게 사용할 수 있다.
- +: 문자열의 경우 이어붙일 수 있다. 단, 숫자는 문자로 변환 후 사용해야 한다.
- -: 리스트의 경우 -1은 마지막 원소, 데이터프레임 변수의 경우 마지막을 선택할 수 있다.

In [ ]:
ser.astype("str") + "세"
## 0    20세
## 1    42세
## 2    39세
## 3    16세
## dtype: object

"y ~ " + " + ".join(["col_A", "col_B", "col_C"])
## 'y ~ col_A + col_B + col_C'

# numpy

In [ ]:
arr = np.arange(6).reshape(2, 3)
arr
## array([[0, 1, 2],
##        [3, 4, 5]])

np.where(arr <= 2, 1, 0)
## array([[1, 1, 1],
##        [0, 0, 0]])

np.r_[2, 4, 6, 12:16]
## array([ 2,  4,  6, 12, 13, 14, 15])

# pandas

In [ ]:
ser = pd.Series([20, 42, 39, 16])
ser.index
## RangeIndex(start=0, stop=4, step=1)

ser.index.values
## array([0, 1, 2, 3], dtype=int64)

In [ ]:
ser.reset_index(drop = True)

In [ ]:
ser.reset_index(drop = False)

In [ ]:
df = pd.DataFrame({"type": ["A", "A", "B", "B"],
                   "value": [15, 20, 25, 30]})
df

In [ ]:
df.index
## RangeIndex(start=0, stop=2, step=1)
df.index.values
## array([0, 1, 2, 3], dtype=int64)
df.columns
## Index(['a', 'b'], dtype='object')
df.columns.values
## array(['type', 'value'], dtype=object)

In [ ]:
df.reset_index()

In [ ]:
df.set_index("type")
df.set_index("type").reset_index() #type col을 맨앞으로

In [ ]:
df = pd.DataFrame({"type": ["A", "A", "B", "B"],
                   "value": [15, 20, 25, 30]})
df

In [ ]:
df.rename(columns = {"type": "group"})

# 요약하기
- .value_counts(normalize=True): 특정 변수의 원소 개수를 세어준다(유일값계산). 
- .groupby(): 특정 변수를 기준으로 묶어서 연산한다. 2개 이상의 변수 선언시 리스트로 묶어준다. 뒤에는 Series 기본 메서드나 .agg()를 붙여 연산한다.
- .where(): 특정 조건이 아닌 것은 결측값으로 만든다. 가끔 np.where() 대신 사용을 하기도 하는데 딱히 사용을 권장하지 않는다.

- pd.crosstab(): 두 변수의 원소간 조합 빈도 확인. .value_counts()와 같이 normalize 인자를 사용하여 다양한 비율을 계산할 수 있다.

### groupby
https://teddylee777.github.io/pandas/pandas-groupby/
df.groupby('col').agg()에서 agg에 넣을수 있는것들

- count	데이터의 개수
- sum	합계
- mean	평균
- median	중앙값
- var, std	분산, 표준편차
- min, max	최소, 최대값
- unique, nunique	고유값, 고유값 개수
- prod	곲
- first, last	첫째, 마지막값

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
filepath=path+"bike.csv"
df=pd.read_csv(filepath)
df.head(4)

In [ ]:
df.groupby('weather').mean()

In [ ]:
df.groupby('weather').agg(['mean','var']) #weather 같은거끼리 묶고, mean도 계산하고 var도 계산하고

In [ ]:
# 컬럼을 평탄화
def flat_cols(df):
    df.columns = [' / '.join(x) for x in df.columns.to_flat_index()]
    return df

#원하는것들끼리, 원하는 함수 적용 가능
df.groupby('weather').agg({ 'temp':'max',
                           'humidity':'mean',
                           'windspeed':['min','max']}).pipe(flat_cols)

In [ ]:
# wheather끼리 묶되, temp랑 humidity 컬럼만 고려할거고, 계산함수는 lambda
df.groupby("weather")[['temp','humidity']].agg(lambda x: x.mean()/x.std())

In [ ]:
df.groupby('weather')[['temp','humidity']].mean().reset_index()

### where

In [ ]:
filepath=path+"iris.csv"
df=pd.read_csv(filepath)
df["is_setosa"] = np.where(df["Species"]=="setosa",1,0) # 특정 조건이면 1, 아니면 0

### crosstab

In [ ]:
df = pd.DataFrame({"type": ["A", "A", "B", "B"],
                   "value": [15, 20, 25, 30]})

In [ ]:
pd.crosstab(df["type"], df["value"], normalize = True) # 전체 중 특정 원소의 비율


In [ ]:
pd.crosstab(df["type"], df["value"], normalize = 1) # column 방향

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

dia=pd.read_csv(path+"diamonds.csv")
df_B=pd.read_csv(path+"elec_load_2017_7d.csv")
dia.head(2)

In [ ]:
pd.crosstab(dia["cut"], dia["clarity"], values=dia["price"], aggfunc=pd.Series.mean).round(3) 
# 클러스터링 하기전에 데이터 구조 바꾸기도 함 

In [ ]:
dia_agg=dia.groupby(["cut","clarity"])["price"].mean().reset_index()
dia_agg.head(10)

In [ ]:
dia_agg.sort_values(["cut","clarity"], ascending=[True,False]).head()

# 피벗
- .melt(): wide form 데이터를 long form 데이터로 변환. 주로 통계처리 직전이나 그래프 그리기 직전의 데이터 모양을 만들 때 사용한다.
- .pivot_table(): long form 데이터를 wide form 데이터로 변환. 데이터를 요약할 수 있으며 주로 군집분석(clustering analysis) 직전의 데이터 모양을 만들 때 사용한다.
- .transpose(): 행렬을 전치시키는 것과 같은 동작을 한다. 활용도는 낮으나 가끔 임시 방편으로 활용하기도 한다.

In [ ]:
#https://fhaktj8-18.tistory.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC-pandasmelt%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%9E%AC%EA%B5%AC%EC%A1%B0%ED%99%94-melt-vs-pivot
df=pd.DataFrame({'store':['Costco','Costco','Costco','Wal-Mart','Wal-Mart','Wal-Mart',"Sam's Club","Sam's Club","Sam's Club"],
               'product':['Potato','Onion','Cucumber','Potato','Onion','Cucumber','Potato','Onion','Cucumber'],
               'price':[3000,1600,2600,3200,1200,2100,2000,2300,3000],
                'quantity':[25,31,57,32,36,21,46,25,9]})
df

In [ ]:
#이렇게 product와 store을 제외한 열들이 
# 'variable' : 컬럼명
# 'value' : 컬럼에 해당하는 값
df.melt(id_vars=['product','store'])

In [ ]:
df.melt(id_vars=['product','store'],value_vars='quantity')

In [ ]:
# 데이터를 요약하거나 군집분석 실시 전 데이터 전처리에 주로 활용
df.pivot(
    index='product',
    columns='store',
    values='price')

In [ ]:
elec=pd.read_csv(path+"/elec_load_2017_7d.csv")
elec_melt=elec.melt(id_vars=["YEAR","MONTH","DAY"])
elec_melt.head(10)

In [ ]:
elec_melt.pivot(index=["YEAR","MONTH","DAY"],columns="variable",values="value") #.reset_index()

# 시간처리

In [ ]:
ser_t_01 = pd.Series(["2077-01-01", "2077-12-28"])
ser_t_01 = pd.to_datetime(ser_t_01)
ser_t_01
## 0   2077-01-01
## 1   2077-12-28
## dtype: datetime64[ns]

ser_t_02 = pd.Series(["2077년 01월 01일", "2077년 12월 28일"])
ser_t_02 = pd.to_datetime(ser_t_02, format = "%Y년 %m월 %d일")
ser_t_02
## 0   2077-01-01
## 1   2077-12-28
## dtype: datetime64[ns]

pd.to_datetime([1,2], origin="2000-01-01",unit="D") # 기준일부터 1D, 2Day 뒤의 값을 반환

In [ ]:
ser_t_01.dt.year
## 0    2077
## 1    2077
## dtype: int64

ser_t_01.dt.month
## 0     1
## 1    12
## dtype: int64

ser_t_01.dt.dayofweek    # weekday인지 확인 필요
## 0    4
## 1    1
## dtype: int64

# 기타 (정리 대기)
- cut() : bins인자에 구간 구분 기준값을 할당하고 labels 인자에는 각 구간에 붙일 이름을 할당한다. 개구간, 폐구간과 관련된 설정인 right 인자의 사용에 유의
- .concat(): 두 개 이상의 데이터프레임을 합침
※ axis 사용에 주의. 인덱스 문제 발생 가능
- .merge(): 두 데이터프레임 병합(join)
※ df1.merge(df2, left_on = “col1”, right_on = “col2”, how = “left”)
※ how: “left”, “right”, “inner”, “outer”
- .sort_values(): 지정 변수 기준 데이터프레임 정렬(오름차순, 내림차순)
- .sample(): 특정 row를 단순 임의 추출
※ n: 정수로 입력하며 row개수 지정, frac: 비율로 입력(0~1)
- pd.get_dummies(): 가변수 생성. 필요시 drop_first = True로 첫 가변수 제거 가능
- ser.shift(2) #2칸 순환,

In [ ]:
filepath=path+"bike.csv"
bike=pd.read_csv(filepath)
bike.head(2)
bike_dum=pd.get_dummies(data=bike,columns=["season"],drop_first=True)

In [ ]:
df=pd.DataFrame([["A",3],["C",1],["B",2]],
               columns=["class","value"])
df.sort_values(by="class")
df.sort_index()

In [ ]:
pd.concat([df_1, df_2])
pd.concat([df_1, df_2], axis=1)
pd.concat([df_1, df_2.reset_index(drop=True)], axis=1)

# string

In [ ]:
str.replace({"aa":"b","abc":"c"})
df.loc[df["col"].str.contains("b"), ] #정규표현식 가능
df["col"].str.split("@",expand=True)# df형태 유지하면서 쪼개서 저장
df["col"].str.split("@").explode().reset_index()
.str.get(-1) #마지막 문자 추출
.slice() #지정된 범위의 문자 추출
.extract() #조건(pat)에 맞는 텍스트 추출하며 group을 지정해야 함.
.lower() #영문 대문자를 영문 소문자로 치환
.zfill() #지정한 길이보다 문자열의 길이가 짧을 경우 앞에 숫자 0을 채워줌

# 결측치, 필터링
- .drop(): 특정 변수 제거 가능
- .dropna(): 결측치가 있는 row 제거 가능
※ how: “any”, “all”
- .fillna(): 결측치를 특정 값으로 치환(Series에도 사용 가능)

In [ ]:
df=pd.read_csv(path+"bike.csv")
df.head()

In [ ]:
df.loc[df["casual"].isin([3,5]),].head(5)

In [ ]:
df.loc[ (df["casual"]==3) & ~(df["registered"]==13) \
       ,].head(5)

In [ ]:
df.loc[[df["casual"].idxmax()],]

In [ ]:
df["season"].unique()

In [ ]:
df.isna().sum()

In [ ]:
df.notnull().head(5)

In [ ]:
df.fillna(value={"Sepal_Length":999,
                   "Sepal_Width":111})
df_na_fill_mean=df_na.fillna(value={"Sepal_Width":df_na["Sepal_Width"].mean()})
df.fillna("hello")
df.info()
df.count()
df.dropna()

# apply

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

filepath=path+"bike.csv"
bike=pd.read_csv(filepath)
bike.head(2)
bike_sub.mean()
bike_sub.apply(func=pd.Series.mean, axis=1)
bike_sub.apply(func = lambda x: round(x.mean()))

# binding, join 병합
- concat
- merge
- join
    - inner join
    - left join
- pandas
    - reset_index
    - set_index

#### concat

In [ ]:
filepath=path+"/bike.csv"
bike=pd.read_csv(filepath)
bike.head(2)
bike_1=bike.iloc[:3,:4]
bike_2=bike.iloc[5:8,:4]
print(bike_1)
print(bike_2)

In [ ]:
pd.concat([bike_1,bike_2])

In [ ]:
pd.concat([bike_1,bike_2.reset_index(drop=True)])

In [ ]:
pd.concat([bike_1,bike_2.reset_index(drop=True)],axis=1)

#### merge
https://yganalyst.github.io/data_handling/Pd_12/

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df_A=pd.read_csv(path+"/join_data_group_members.csv")
df_B=pd.read_csv(path+"/join_data_member_room.csv")

In [ ]:
# 아무 옵션 적용 X, 
## pd.merge(df1, df2)
#: 공통적인 컬럼을 기준으로 inner조인

## pd.merge(df1,df2, how='outer',on='id')
#: id를 기준으로 합침. 단 어느한쪽에라도 없는 데이터가 있으면 NaN지정.

## pd.merge(df1,df2, how='left', left_on='stock_name', right_on='name')
#: left df를 기준으로, left df의 컬럼명과 right의 컬럼을 비교하는데,
#: 합칠때는 left df의 고윳값만 살리고 나머지는 버림.

In [ ]:
df_A.head(2)

In [ ]:
df_B.head(2)

In [ ]:
## 기준열 이름이 다를 때 **_on 이렇게 컬럼명 지정
# how inner라서 공통적인것만 추출
pd.merge(left=df_A, right=df_B, left_on="member", right_on="name",how="inner") 

#### join

In [ ]:
# df1.set_index('id', inplace=True)
# df2.set_index('id', inplace=True)
# df1.join(df2, how='inner')